const data = {
  products: [
    {
      name: 'Casual Printed Red Top',
      slug: 'casual-printed-red-top',
      category: 'Tops',
      image: '/images/p1.png',
      price: 360,
      countInstock: 10,
      brand: 'Urbanic',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality top',
    },
    {
      name: 'Casual Solid Black Top',
      slug: 'casual-solid-black-top',
      category: 'Tops',
      image: '/images/p2.png',
      price: 300,
      countInstock: 12,
      brand: 'Harpa',
      rating: 4.3,
      numReviews: 8,
      description: 'High quality product',
    },
    {
      name: 'Graphic Print Pink T-Shirt',
      slug: 'graphic-print-pink-t-shirt',
      category: 'T-Shirt',
      image: '/images/p3.png',
      price: 600,
      countInstock: 15,
      brand: 'Puma',
      rating: 4.8,
      numReviews: 15,
      description: 'High quality product',
    },
    {
      name: 'Graphic Print Purple T-Shirt',
      slug: 'graphic-print-purple-t-shirt',
      category: 'T-shirt',
      image: '/images/p4.png',
      price: 550,
      countInstock: 8,
      brand: 'Nike',
      rating: 4.2,
      numReviews: 13,
      description: 'High quality T-shirt',
    },
  ],
};

export default data;
